version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15673:15672
    mem_limit: 3221225472
  registry:
    image: mice/registry
    restart: always
    ports:
      - "6501:6501"
    mem_limit: 2147483648
  config:
    image: mice/config
    restart: always
    ports:
      - "6502:6502"
    mem_limit: 2147483648
    environment:
      - "CONFIG-PATH=qa"
  monitor:
    image: mice/monitor
    restart: always
    ports:
      - "6533:6533"
    mem_limit: 2147483648
  zipkin:
    image: mice/zipkin
    restart: always
    ports:
      - "6504:6504"
    mem_limit: 2147483648
    environment:
      - "SPRING_PROFILES_INCLUDE=qa"
  gateway:
    image: mice/gateway
    ports:
      - "6505:6505"
    restart: always
    mem_limit: 3221225472
  media-service:
    image: mice/media-service
    restart: always
    ports:
      - "6506:6506"
    volumes:
      - /data/log/mice-media.log:/data/log/mice-media.log
    mem_limit: 3221225472
  setting-service:
    image: mice/setting-service
    restart: always
    ports:
      - "6507:6507"
    volumes:
      - /data/log/mice-setting.log:/data/log/mice-setting.log
    mem_limit: 3221225472
  news-service:
    image: mice/news-service
    restart: always
    ports:
      - "6508:6508"
    volumes:
      - /data/log/mice-news.log:/data/log/mice-news.log
    mem_limit: 3221225472
  task-service:
    image: mice/task-service
    restart: always
    ports:
      - "6509:6509"
    volumes:
      - /data/log/mice-task.log:/data/log/mice-task.log
    mem_limit: 3221225472
  analysis-service:
    image: mice/analysis-service
    restart: always
    ports:
      - "6510:6510"
    volumes:
      - /data/log/mice-analysis.log:/data/log/mice-analysis.log
    mem_limit: 3221225472
  logs-service:
    image: mice/logs-service
    restart: always
    ports:
      - "6511:6511"
    volumes:
      - /data/log/mice-logs.log:/data/log/mice-logs.log
    mem_limit: 3221225472
  schedule-service:
    image: mice/schedule-service
    restart: always
    ports:
      - "6512:6512"
    volumes:
      - /data/log/mice-schedule.log:/data/log/mice-schedule.log
    mem_limit: 3221225472
  message-service:
    image: mice/message-service
    restart: always
    ports:
      - "6513:6513"
    mem_limit: 3221225472
  file-service:
    image: mice/file-service
    ports:
      - "6514:6514"
    volumes:
      - /data/static/upload/:/data/static/upload/
      - /data/log/mice-file.log:/data/log/mice-file.log
    restart: always
    mem_limit: 3221225472
  redis-service:
    image: mice/redis-service
    restart: always
    ports:
      - "6515:6515"
    mem_limit: 3221225472
  elasticsearch-service:
    image: mice/elasticsearch-service
    restart: always
    ports:
      - "6516:6516"
    mem_limit: 3221225472