server:
  port: 6516
  max-http-header-size: 52428800
  tomcat:
    max-connections: 3000
    max-http-post-size: 52428800
    max-threads: 1000


eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

elasticsearch-config:
  host: http://106.75.126.48:9200

