server:
  port: 6508

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

spring:
  datasource:
#    url: jdbc:mysql://106.75.31.202:3306/mice_com?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://%s:3306/%s?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: gd%dqx34hPA
    driver-class-name: com.mysql.jdbc.Driver
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
  task:
    pool:
      corePoolSize: 5
      maxPoolSize: 50
      keepAliveSeconds: 60
      queueCapacity: 1000
  http:
    multipart:
      max-file-size: 20971520      # Max file size，默认1M
      max-request-size: 20971520   # Max request size，默认10M

# Java类配置 并不能读取到mapper的xml文件在哪  所以以下配置失效
#mybatis:
#  type-aliases-package: common.entity.news
#  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback.xml