server:
  port: 6510

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

spring:
  datasource:
    url: jdbc:mysql://10.9.123.219:3306/mice_com?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: gd%dqx34hPA
    driver-class-name: com.mysql.jdbc.Driver
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
  task:
    pool:
      corePoolSize: 5
      maxPoolSize: 50
      keepAliveSeconds: 60
      queueCapacity: 1000
  http:
    multipart:
      max-file-size: 20971520      # Max file size，默认1M
      max-request-size: 20971520   # Max request size，默认10M

mybatis:
  type-aliases-package: common.entity.analysis
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback.xml