eureka:
  instance:
    hostname: 10.9.66.108
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${REGISTRY_SERVER_USER:admin}:${REGISTRY_SERVER_PASSWORD:meihua6666666}@${eureka.instance.hostname}:6501/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    host: 10.9.66.108
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
