spring:
  datasource:
    url: jdbc:mysql://10.9.123.219:3306/mhcore_message?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 5dTJ67vrrse23X
    driver-class-name: com.mysql.jdbc.Driver
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false

server:
  port: 6513

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

mybatis:
  type-aliases-package: entity.message
  mapper-locations: classpath:mapper/*.xml

